### ISSUE TITLE
Sublime Text 3 Support

### ISSUE THREAD

**Issue by pilleye** [pilleye/jumpstart#5]
- [x] Install Sublime Text 3 with Homebrew Cask
- [x] Set to optional install.
- [x] If `zsh` is installed, setup Sublime Text plugin
- [ ] Install Plugins

**Comment by pilleye** [comment]
@johnwyles hey, if you could help here that'd be great.

**Comment by johnwyles** [comment]
I haven't forgot about you - I am busy with my own side project but if you keep up some momentum I think this project is commendable - keep in mind making it easy to update versions, add/remove things easily for customization (I know you probably already know that - just want to give you some more motivation!)
